# Generated by Django 4.2.1 on 2023-05-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samolet", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="building",
            old_name="flats_on_floor",
            new_name="floors_total",
        ),
        migrations.AddField(
            model_name="building",
            name="section_total",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
