# Generated by Django 4.2.1 on 2023-05-28 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("samolet", "0003_remove_section_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="flat",
            name="building",
            field=models.ForeignKey(
                default=303,
                on_delete=django.db.models.deletion.PROTECT,
                to="samolet.building",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="flat",
            name="number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="flat",
            name="floor",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="flat",
            name="section",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Floor",
        ),
        migrations.DeleteModel(
            name="Section",
        ),
    ]
