# Generated by Django 4.2.1 on 2023-05-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samolet", "0004_flat_building_flat_number_alter_flat_floor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "samolet_pk",
                    models.IntegerField(primary_key=True, serialize=False, unique=True),
                ),
                ("floors_total", models.IntegerField(blank=True, null=True)),
                ("number", models.IntegerField(blank=True, null=True)),
                ("flats_on_floor", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="flat",
            name="section",
        ),
    ]
