# Generated by Django 4.2.1 on 2023-05-28 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("samolet", "0005_section_remove_flat_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="flat",
            name="section",
            field=models.ForeignKey(
                default=960,
                on_delete=django.db.models.deletion.PROTECT,
                to="samolet.section",
            ),
            preserve_default=False,
        ),
    ]
