# Generated by Django 4.2.1 on 2023-05-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("samolet", "0006_flat_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flat",
            name="building",
        ),
    ]
