# Generated by Django 4.2.1 on 2023-05-28 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("samolet", "0008_rename_protject_building_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="building",
            field=models.ForeignKey(
                default=303,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="section_building",
                to="samolet.building",
            ),
            preserve_default=False,
        ),
    ]
