# Generated by Django 4.2.1 on 2023-05-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samolet", "0009_section_building"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="is_analysed",
            field=models.BooleanField(default=False),
        ),
    ]
