# Generated by Django 4.2.1 on 2023-05-28 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("samolet", "0010_check_is_analysed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="check",
            old_name="Flat",
            new_name="flat",
        ),
    ]
