# Generated by Django 4.2.1 on 2023-06-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samolet", "0014_remove_check_is_analysed_flat_ready_precentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="is_analysed",
            field=models.BooleanField(default=False),
        ),
    ]
