# Generated by Django 4.2.1 on 2023-06-07 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samolet", "0015_check_is_analysed"),
    ]

    operations = [
        migrations.AddField(
            model_name="flat",
            name="square",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
