# Generated by Django 4.2.1 on 2023-06-08 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samolet", "0017_alter_check_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
