# Generated by Django 4.2.1 on 2023-06-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("samolet", "0018_alter_check_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="check",
            name="analys_image",
            field=models.ImageField(blank=True, null=True, upload_to="analys_images/"),
        ),
        migrations.AddField(
            model_name="check",
            name="analys_square",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
