# Generated by Django 4.2.1 on 2023-06-10 14:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("samolet", "0019_check_analys_image_check_analys_square"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="analys_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="analys_images/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "png", "", "*"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="check",
            name="flat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="checks",
                to="samolet.flat",
            ),
        ),
    ]
